### ISSUE TITLE
Prebuilds for v6.3.3

### ISSUE THREAD

**Issue by quanru** [kesla/node-snappy#189]

**Comment by keyesdav** [comment]
also having a problem with snappy 6.3.3 and npm install.  any guidance on how to get my npm install to work again?  looks like linked against a newer libstdc than I have.  see the following error...

> snappy@6.3.3 install /scratch/dkeyes/gitlocal/insight-microservices/product/node/services/insight/associationmanager/node_modules/snappy
> prebuild-install || node-gyp rebuild

prebuild-install WARN install /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /scratch/dkeyes/gitlocal/insight-microservices/product/node/services/insight/associationmanager/node_modules/snappy/build/Release/binding.node)
make: Entering directory `/scratch/dkeyes/gitlocal/insight-microservices/product/node/services/insight/associationmanager/node_modules/snappy/build'
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.7/snappy-sinksource.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.7/snappy-stubs-internal.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.7/snappy.o
  AR(target) Release/obj.target/deps/snappy/snappy.a
  COPY Release/snappy.a
  SOLINK_MODULE(target) Release/obj.target/binding.node
g++: error: Release/obj.target/binding/src/binding.o: No such file or directory
make: *** [Release/obj.target/binding.node] Error 1
make: Leaving directory `/scratch/dkeyes/gitlocal/insight-microservices/product/node/services/insight/associationmanager/node_modules/snappy/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/scratch/oic-mt/apps/node-v10.15.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.1.12-124.27.1.el7uek.x86_64
gyp ERR! command "/scratch/oic-mt/apps/node-v10.15.3-linux-x64/bin/node" "/scratch/oic-mt/apps/node-v10.15.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /scratch/dkeyes/gitlocal/insight-microservices/product/node/services/insight/associationmanager/node_modules/snappy
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

**Comment by whomobile** [comment]
fyi:  see https://github.com/kesla/node-snappy/pull/191

**Comment by chiahrens** [comment]
I'm also getting  /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /test/node_modules/snappy/build/Release/binding.node)

Trying to upgrade glibc:
# sudo yum install libstdc++
Loaded plugins: ovl
Package libstdc++-4.8.5-28.el7_5.1.x86_64 already installed and latest version
Nothing to do

But the current glibc shows:
# strings /usr/lib64/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_DEBUG_MESSAGE_LENGTH

**Comment by whomobile** [comment]
> I'm also getting /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /test/node_modules/snappy/build/Release/binding.node)
> sudo yum install libstdc++

@chiahrens I am using CenOS 7.7.x and default centOS yum repos, and /usr/lib64/libstdc++.so.6.0.19 (and I don't see GLIBCXX_3.4.21 string inside lib), but I could npm install after chaning .npmignore.

**Comment by kesla** [comment]
My assumption is that this was fixed in 6.3.4

**Comment by quanru** [comment]
it seems still not work
![image](https://user-images.githubusercontent.com/11739753/80353794-78281f00-88a8-11ea-90a6-5739b134e211.png)

**Comment by kesla** [comment]
@quanru there are no prebuilds available for CentOS so instead the module tries to build from source, but it doesn't seem like you have what's needed to build C++ modules.

The error message complains about make.

**Comment by kesla** [comment]
Maybe @whomobile can help out even more on getting this built on CentOS?

**Comment by whomobile** [comment]
Sure, I will check again and let you know.

**Comment by quanru** [comment]
> @quanru, your error is
> 
> > gyp ERR! stack Error: not found: make
> 
> Can you check whether you have /usr/bin/make ?
> `ls -l /usr/bin/make`
> 
> if you don't have make, and you have sudo/root access, you might want to try in install development tools.
> `sudo yum group install "Development Tools"`
> 
> If you want to debug issues, you might want to test
> `prebuild-install --debug --force`
> 
> Here is from my CentOS Docker.
> 
> ```
> [root@d1f20515c63d node-snappy]# cat /etc/redhat-release
> CentOS Linux release 7.7.1908 (Core)
> [root@d1f20515c63d app]# node-gyp  configure
> gyp info it worked if it ends with ok
> gyp info using node-gyp@6.1.0
> gyp info using node@11.15.0 | linux | x64
> ..
> [root@d1f20515c63d node-snappy]# npm run install
> 
> > snappy@6.3.4 install /usr/src/app/node-snappy
> > prebuild-install || node-gyp rebuild
> 
> sh: prebuild-install: command not found
> make: Entering directory  /usr/src/app/node-snappy/build'
>   CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.7/snappy-sinksource.o
>   CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.7/snappy-stubs-internal.o
>   CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.7/snappy.o
>   AR(target) Release/obj.target/deps/snappy/snappy.a
>   COPY Release/snappy.a
>   CXX(target) Release/obj.target/binding/src/binding.o
>   SOLINK_MODULE(target) Release/obj.target/binding.node
>   COPY Release/binding.node
> make: Leaving directory /usr/src/app/node-snappy/build'
> [root@d1f20515c63d node-snappy]#
> [root@d1f20515c63d node-snappy]# npm install -g prebuild-install
> /usr/local/bin/prebuild-install -> /usr/local/lib/node_modules/prebuild-install/bin.js
> + prebuild-install@5.3.3
> added 60 packages from 37 contributors in 4.755s
> [root@d1f20515c63d node-snappy]# prebuild-install --debug --force
> prebuild-install WARN install prebuilt binaries enforced with --force!
> prebuild-install WARN install prebuilt binaries may be out of date!
> prebuild-install WARN install No prebuilt binaries found (target=11.15.0 runtime=node arch=x64 libc= platform=linux)
> [root@d1f20515c63d node-snappy]#
> ```

but it is ok with v6.2.3

**Comment by whomobile** [comment]
> but it is ok with v6.2.3
@quanru It looks kesla added prebuilds. you might want to try again. 
if still not working,  can you tell centos release that you are using?

**Comment by quanru** [comment]
@whomobile it is ok now:

![image](https://user-images.githubusercontent.com/11739753/80664834-632ad600-8aca-11ea-980d-698e45d1bd96.png)
